### ISSUE TITLE
Fix 'Complex Method' issue in src\org\usfirst\frc\team4990\robot\subsystems\Elevator.java

### ISSUE THREAD

**Issue by benjamin-antupit** [Gryphon-Robotics-4990/2018#33]
[CodeFactor](https://www.codefactor.io/repository/github/gryphon-robotics-4990/2018) found an issue: Complex Method

It's currently on:
[src\org\usfirst\frc\team4990\robot\subsystems\Elevator.java:46-84
](https://www.codefactor.io/repository/github/gryphon-robotics-4990/2018/source/master/src/org/usfirst/frc/team4990/robot/subsystems/Elevator.java#L46)Commit 3aa627afc662d3c164ed5102837713767a20e7b9

**Comment by MajikalExplosions** [comment]
I thought that this was fixed?
