### ISSUE TITLE
Test SensorStop

### ISSUE THREAD

**Issue by benjamin-antupit** [Gryphon-Robotics-4990/2018#41]
See PR #42 
- [x] rename to `sensor stop`
- [x] change constructor to `public SensorStop(SensorBase sensor, double endCondition, Command command)`
- [x] figure out how to determine =, <, >, ≤ or ≥
- [x] set end condition
- [x] start command on init
- [x] stop command on end
- [ ] test with different conditions on robot:
    - [ ] driving straight and base encoder
    - [ ] turning and gyro
    - [ ] elevator and elevator encoder

**Comment by MajikalExplosions** [comment]
does this still apply is this done

**Comment by benjamin-antupit** [comment]
We still need to:
- [x] figure out how to determine =, <, >, ≤ or ≥
- [x] set end condition
- [x] start command on init
- [x] stop command on end

(there's more, see the original issue.)

**Comment by benjamin-antupit** [comment]
forget this, it's pretty good.
